"""Initial migration with all models

Revision ID: a911d2ca9cea
Revises: a752f65bab4c
Create Date: 2026-05-09 14:23:09.757912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a911d2ca9cea'
down_revision = 'a752f65bab4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
